Auth and crud
FIT-2024-Digital-Library/digital-library-back pull request #11
Opened 2024-11-13 02:56 UTC by IgorShal

2024-11-13 02:59 UTC, IgorShal commented
Сейчас сделано: routes: /register, /books/id, /books/, /authors/id,/authors/, /genres/id, /genres/

2024-11-13 07:03 UTC, AntonTsoy requested changes
Я прочитал и поревьюил где-то 80% твоего кода, к остальным 20% я пока не готов

2024-11-13 07:03 UTC, AntonTsoy commented on app/db/database.py
> +async_session_maker = async_sessionmaker(db_engine, expire_on_commit=False)
Вернемся к теме ORM vs Core

1) Если мы используем ORM, то тогда модели базы данных нужно переписать с Table на классы. Прикол ORM в том, что мы работаем с удобными Python объектами.
2) Если мы используем Core, надо избавиться от async_sessionmaker.

P.S. Я уже запутался в том, как работает под капотом SQLAlchemy Session и Connection. Нужно заняться ресерчем этой темы и мне и тебе

2024-11-13 16:19 UTC, AntonTsoy commented on app/routes/books.py
> +        return [Book(**book._mapping) for book in books]
Ладно, это не обязательно, только если захочешь. Но тебе все равно нужно её переписать с учетом деления на CRUD и ROUTES

2024-11-14 09:35 UTC, KozlovKV commented on app/routes/authors.py
> +from app.schemas import *
Кстати, а что скажешь насчёт `import app.schemas as <name>`?

2024-11-14 12:02 UTC, AntonTsoy commented on app/routes/authors.py
> +from app.schemas import *
Мне не очень это нравится. Я ниже писал про возможные варианты. В том числе скопировал предложенный Т-куратором прием с определением all. Так мы сможем писать: `from app import schemas`

2024-11-14 12:05 UTC, AntonTsoy commented on app/db/database.py
>  class PostgresSettings(BaseSettings):
Можешь пока с этим ничего не делать. Я просто это как фан факт говорю

2024-11-18 12:31 UTC, IgorShal commented on app/routes/authors.py
> +from app.db.database import *
Fuck u without negative

2024-11-18 12:39 UTC, IgorShal commented on app/schemas/users.py
> +class UserRegister(BaseModel):
Потому что это модель регистрации пользователя, а не пользователя

2024-11-19 05:50 UTC, KozlovKV requested changes
По большей части вроде всё неплохо)

Ждём роутов для логина и профиля + CREATE/PUT/DELETE-запросов с соответствующими крудами

2024-11-19 05:50 UTC, KozlovKV commented on app/crud/authors.py
> +
Ещё добавить бы сюда получение автора по имени

2024-11-19 05:50 UTC, KozlovKV commented on app/crud/books.py
> +            author_id = await session.execute(select(author_table.c.id).where(author_table.c.name == author))
И тогда здесь можно будет просто вызывать функцию круда для авторов

2024-11-19 05:50 UTC, KozlovKV commented on app/crud/books.py
> +            genre_id = await session.execute(select(genre_table.c.id).where(genre_table.c.name == genre))
То же самое для жанров

2024-11-19 05:50 UTC, KozlovKV commented on app/db/models.py
> +    Column("name", ForeignKey(genre_table.c.id), nullable=True),
Имя?

2024-11-19 05:50 UTC, KozlovKV commented on app/db/models.py
>      Column("image", LargeBinary, nullable=True),
Как ты и предлагал, замени тип поля также на строку со ссылкой

2024-11-19 05:50 UTC, KozlovKV commented on app/routes/books.py
> +        id: Optional[int] = Query(None, description="Filter by book ID"),
query-аргументы, особенно если их много, очень желательно выносить в pydantic-схему

2024-11-19 05:50 UTC, KozlovKV commented on app/routes/books.py
> +        id: Optional[int] = Query(None, description="Filter by book ID"),
@AntonTsoy , мы ведь можем так делать? Просто поймал себя на мысли, что у нас прежде такого кейса не было

2024-11-19 05:50 UTC, KozlovKV commented on app/routes/books.py
> +        raise HTTPException(status_code=404, detail="No books found matching the criteria")
Пустой список при запросе множества функция - это не самая плохая ситуация. Вопрос несколько дискуссионный, но я думаю, тут можно просто возвращать список, не проверяя, есть ли в нём вообще что-то

2024-11-19 05:50 UTC, KozlovKV commented on app/routes/authors.py
> +        raise HTTPException(status_code=404, detail="No authors in db")
То же самое

2024-11-19 05:50 UTC, KozlovKV commented on app/routes/genres.py
> +        raise HTTPException(status_code=404, detail="No genres in db")
И тут

2024-11-19 05:50 UTC, KozlovKV commented on app/routes/users.py
> +    async with async_session_maker() as session:
Работу с API БД надо вынести в круд-файлик для пользователя

2024-11-25 12:43 UTC, IgorShal commented
Кроме юзеров так то крад есть для всех

2024-11-25 12:43 UTC, IgorShal commented
Но надо будет везде with session убрать и переставить в routes

2024-11-25 12:48 UTC, IgorShal commented
НУ ещё пока там везде только обычная регистрация требуется, но это для теста, потом админов добавлю

2024-11-27 09:54 UTC, AntonTsoy commented on app/routes/books.py
> +        id: Optional[int] = Query(None, description="Filter by book ID"),
Можем. Вот нашел статью в документации:
https://fastapi.tiangolo.com/tutorial/query-param-models/

2024-12-01 07:32 UTC, KozlovKV requested changes
Обнови `requirements` 🥺

2024-12-03 06:07 UTC, KozlovKV requested changes
По стилю смотрел не особо внимательно (Антону это вверяю), больше по функционалу

2024-12-03 06:07 UTC, KozlovKV commented on app/schemas/books.py
> +    author: str
**Fix:**

И в схемке тут поменяй типы для автора и жанра

2024-12-03 06:07 UTC, KozlovKV commented on app/routes/books.py
> +async def create_book(book: CreateBook, user_data: User = Depends(get_current_user)):
**Comment:**

Я верно понимаю, что для того, чтобы сделать обязательными админские права, надо просто `get_current_user` поменять на `get_current_admin_user`

2024-12-03 06:07 UTC, KozlovKV commented on app/routes/books.py
> +async def create_book(book: CreateBook, user_data: User = Depends(get_current_user)):
**Improvement:**

Если так, то поменяй там, где это нужно, а для создания админ-юзера напиши пока что просто файлик (как `create_tables.py`), принимающий имя и пароль как аргументы

2024-12-03 06:15 UTC, IgorShal commented on app/routes/users.py
> +    response.delete_cookie(key="users_access_token")
не

2024-12-03 06:53 UTC, IgorShal commented
@IgorShal лучший, ничего не надо менять !! Щас аппрувну

2024-12-03 09:03 UTC, AntonTsoy commented
Обещаю, что в течение первых двух секунд, как Дональд Трамп вступит в должность президента, я дам апрув этому PR-у

2024-12-03 10:40 UTC, AntonTsoy commented
Я наконец-то провел ресерч темы `Session` vs `Connection`. Пришел к выводу, что мы можем продолжать использовать async_sessionmaker даже работая в Core стиле.

У нас маленький проект, нет больших нагрузок, поэтому мы не будем испытывать сложностей с накладными расходами на управление состоянием объектов. Мы можем обойтись без сложных SQL запросов и транзакций.

2024-12-03 11:14 UTC, AntonTsoy requested changes
В принципе мне стало плевать на качество кода, осталось мало времени до защиты, надо быстрее писать, поэтому если работает, то уже отлично. Оба моих замечания носят характер советов на будущее, соблюдать их очень просто. Я отметил то, что сразу бросилось мне в глаза, когда я открыл код, а вообще я его не читал.

И ещё одно, ты как-то хотел сделать удержание одной сессии на круд операцию. Пруфы смотри ниже. Если ещё есть желание, то сделай, это сделает запросы к БД эффективнее. Если нет, то ок, отпишись, и я дам апрув.

![изображение](https://github.com/user-attachments/assets/bf73ad68-5cd0-48f8-985a-040fe202ee0e)

2024-12-03 11:14 UTC, AntonTsoy commented on app/crud/authors.py
> +        if id is not None:
КАК ТАК ТО???? Я НЕ ВЕРЮ, что не знал, что в python есть встроенная функция id().

Ладно, это не вызывает ошибок. Закроем на это глаза, в следующий раз в аналогичной ситуации лучше называй переменную idx

2024-12-03 11:14 UTC, AntonTsoy commented on app/crud/books.py
> +from fastapi import HTTPException, Depends
мне нетрудно будет самому удалить неиспользуемые импорты, но лучше их конечно не оставлять. Ты же в PyCharm пишешь?

2024-12-03 13:21 UTC, KozlovKV requested changes

2024-12-03 13:21 UTC, KozlovKV commented on app/routes/users.py
>  @router.get('/profile', response_model=None, summary='Returns authorized user')
Поменяй модель на ту, которая тут действительно возвращается. И если где-то ещё также, то исправь. Это критически важно для фронта

2024-12-04 04:10 UTC, IgorShal commented on app/routes/genres.py
> +        name: Optional[str] = Query(None, description="Find by genre name")):
ne

2024-12-04 04:10 UTC, IgorShal commented on app/routes/genres.py
> +async def get_genres(
nahera

2024-12-04 04:10 UTC, IgorShal commented on app/routes/authors.py
> +async def get_authors(
nahera

2024-12-04 04:45 UTC, IgorShal commented on app/schemas/books.py
> +    author: str
Нет, тут всё верно

2024-12-04 04:46 UTC, IgorShal commented on app/schemas/books.py
> +    author: str
Потому что тут я уже логику получения по имени автора айдишника сделал

2024-12-04 04:46 UTC, IgorShal commented on app/schemas/books.py
> +    author: str
МЫ можем в запросе имя автора писать и оно само подключится к существующему айдишнику либо новый создаст

2024-12-04 04:47 UTC, IgorShal commented on app/crud/authors.py
> +        if id is not None:
я знаю, мне просто впдалу меняять

2024-12-04 04:49 UTC, IgorShal commented on app/crud/books.py
> +from fastapi import HTTPException, Depends
ну это уж слишком, мне че делать нечего, как импорты ненужные каждые пять минут удялть

2024-12-04 05:47 UTC, IgorShal commented on app/routes/genres.py
> +        name: Optional[str] = Query(None, description="Find by genre name")):
Теперь проверятся неполное соответствие

2024-12-04 06:15 UTC, IgorShal commented
Всё я заколебался, некст правки через неделю

2024-12-04 09:15 UTC, AntonTsoy commented on app/crud/books.py
> +from fastapi import HTTPException, Depends
ХПАХАХХ, ну да

2024-12-04 09:17 UTC, AntonTsoy commented on app/crud/authors.py
> +        if id is not None:
Я не прошу ничего менять. И тут об этом писал и в комменте выше. Но вообще когда пишешь какую-то функцию, написать idx вместо id вроде несложно

2024-12-08 07:07 UTC, AntonTsoy commented on app/users/auth.py
Done. Сделал пакет settings и utils. Во второй закинул логику, которую не понятно куда отнести. Есть нюанс... Из-за циклических импортов придется явно обращаться к `utils.auth`, поэтому не удивляйтесь, когда увидите такие строки:
```python
from app.utils import CrudException
from app.utils.auth import get_current_user
```

2024-12-08 07:30 UTC, AntonTsoy commented on app/routes/books.py
> +async def create_book(book: CreateBook, user_data: User = Depends(get_current_user)):
`create_tables.py` больше нет, я его удалил. Теперь у нас есть нормальная входная точка проекта

2024-12-08 08:23 UTC, KozlovKV approved these changes
Кое-какие моменты ввиду критичности поменяли, но это не значит, что работы не осталось вовсе.

В частности, проверка прав пользователей всё ещё актуальна.

Как её сделаешь, можешь вливать (ну и некритическую ошибку пофиксить будет неплохо)

2024-12-08 08:23 UTC, KozlovKV commented on app/routes/books.py
> +@router.put('/{book_id}/update', response_model=Book,
**Non-critical error:**

При вводе несуществующего ID все осатльные роуты нормально выживают, а этот падает с 500-й ошибкой

2024-12-08 08:23 UTC, KozlovKV commented on app/crud/books.py
> +        genre_id = await get_existent_or_create_genre_in_db(genre_creation_model)
**Comment:**

Я чутка переосмыслил свою жизнь, так что пускай остаётся так. Работает вроде неплохо, а лишняя работа нам ни к чему

2024-12-08 08:23 UTC, KozlovKV commented on app/routes/books.py
> +async def create_book(book: CreateBook, user_data: User = Depends(get_current_user)):
Но первого админского пользователя нам всё равно надо будет как-то создать некрасивым способом...

А дальше да, админ через роуты должен иметь возможность других админами делать

2024-12-08 08:52 UTC, AntonTsoy commented on app/crud/books.py
> +        genre_id = await get_existent_or_create_genre_in_db(genre_creation_model)
Правильно

2024-12-08 08:54 UTC, AntonTsoy commented on app/routes/books.py
> +async def create_book(book: CreateBook, user_data: User = Depends(get_current_user)):
можно после создания всех таблиц сделать вызов функции, которая создаст админа
```python
@asynccontextmanager
async def lifespan(app: FastAPI):
    await create_tables()
    await create_admin()  # что-то такое
    yield
    await close_connections()
```

2024-12-08 09:05 UTC, AntonTsoy approved these changes
Lol didn't read

2024-12-08 16:57 UTC, IgorShal commented
> В принципе мне стало плевать на качество кода, осталось мало времени до защиты, надо быстрее писать, поэтому если работает, то уже отлично. Оба моих замечания носят характер советов на будущее, соблюдать их очень просто. Я отметил то, что сразу бросилось мне в глаза, когда я открыл код, а вообще я его не читал.
> 
> И ещё одно, ты как-то хотел сделать удержание одной сессии на круд операцию. Пруфы смотри ниже. Если ещё есть желание, то сделай, это сделает запросы к БД эффективнее. Если нет, то ок, отпишись, и я дам апрув.
> 
> ![изображение](https://private-user-images.githubusercontent.com/112404841/391938210-bf73ad68-5cd0-48f8-985a-040fe202ee0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjM5MjcsIm5iZiI6MTczMzY2MzYyNywicGF0aCI6Ii8xMTI0MDQ4NDEvMzkxOTM4MjEwLWJmNzNhZDY4LTVjZDAtNDhmOC05ODVhLTA0MGZlMjAyZWUwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxMzEzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzBiOGMwZmViOTY3M2M0MGY2NDZiY2M3MDlkOTM1YTQwMzhhY2ExM2MzMTQxZjdiMmVkMGQ4NmZkNjc0MDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W7Wl-t-QTh_JwbzUGkXePtQdxEVe9nSgAl9Wh4j44Fk)

Пофиксил

2024-12-11 08:00 UTC, merged