NOT READY YET
FIT-2024-Digital-Library/digital-library-back pull request #20
Opened 2024-12-14 14:33 UTC by IgorShal

2024-12-16 11:09 UTC, KozlovKV requested changes
Круто! Почти так, как я это представлял

Кроме того, что я написал в комментах, влей к себе ветку `develop`, чтобы в схему для книги добавилось `theme_id`, потому что сейчас работа с книгами почти невозможна (в БД поле есть, оно обязательное, а бэкэнд о нём не знает)

2024-12-16 11:09 UTC, KozlovKV commented on app/routes/storage.py
Здесь на загрузку и удаление тоже добавь проверку на модератора

2024-12-16 11:13 UTC, IgorShal commented on app/routes/users.py
> +async def get_admin_role(user_id: int, privilege: PrivilegesEnum, user_creds: User = Depends(get_current_user)):
eh

2024-12-16 11:13 UTC, IgorShal commented on app/routes/users.py
> +async def get_admin_role(user_id: int, privilege: PrivilegesEnum, user_creds: User = Depends(get_current_user)):
я специально сделал чтоб тестить

2024-12-17 16:23 UTC, IgorShal commented
@KozlovKV Короче админку теперь получать будет самый первый пользователь, потому что создавать пользователя админа мне не нравится, + я поменял логику апдейта для юзеров и книг: теперь все поля опшиналы, то есть ты в своих запросах можешь менять что угодно

2024-12-17 16:24 UTC, IgorShal commented
+ адпейтить юзеры могут только себя если они не админы, удалять тоже могут только себя если не админы, наверное тоже самое надо для отзывов седлать

2024-12-17 16:24 UTC, IgorShal commented
А стоп, ты вроде это делал уже

2024-12-19 18:36 UTC, KozlovKV approved these changes

2024-12-19 18:36 UTC, merged